### ISSUE TITLE
Default bin/setup file does not configure database correctly

### ISSUE THREAD

**Issue by ottony** [mateusmedeiros/generator-prelude#2]
When used `bin/setup` an error occur because does not exists a `db/schema.rb` file.

```
db/schema.rb doesn't exist yet. Run `rails db:migrate` to create it, then try again. If you do not intend  to use a database, you should instead alter config/application.rb to limit the frameworks that will be loaded.
```

changing `rake db:setup` to `rake db:create db:migrate` or just commiting an initial `schema.rb` probably will solve that.

**Comment by mateusmedeiros** [comment]
@ottony You should use the setup generator to setup your app, instead of bin/setup. The generated readme already points that out, though.

I'm not sure if that is the best solution, so I may change that in the future, but that's how it is for now.
